name: Deploy to GitHub Pages

on:
  push:
    branches:
      - hugo

jobs:
  generation:
    name: 💾 Generation
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build Link Index
        uses: jackyzha0/hugo-obsidian@v2.12
        with:
          index: true
          input: content
          output: assets/indices
          root: .

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.92.2'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master  # deploying branch

  web-deploy:
    name: 🎉 Deploy
    needs: generation
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
      with:
        ref: master
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.ftp_host }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: /blog.aquitano.ga/htdocs/